# Generated by Django 6.0.2 on 2026-03-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('picture', models.FileField(default='images/default.jpg', upload_to='images/')),
                ('description', models.TextField()),
                ('discount', models.IntegerField()),
                ('badge_text', models.CharField(max_length=50)),
                ('weight_unit', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
    ]
