# Generated by Django 6.0.2 on 2026-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='picture',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
