# Generated by Django 6.0.2 on 2026-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0004_product_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_icon', models.CharField(default='📦', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
