# Generated by Django 6.0.2 on 2026-03-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
