# Generated by Django 6.0.2 on 2026-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='status',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_picture',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
