# Generated by Django 6.0.2 on 2026-06-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.categories'),
        ),
    ]
