# Generated by Django 6.0.2 on 2026-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
